# Bloque del servidor para redirigir todo el tráfico HTTP (puerto 80) a HTTPS
server {
    listen 80;
    server_name bioia.redclara.net;

    # Redirecciona permanentemente a la versión segura (HTTPS)
    return 301 https://$host$request_uri;
}

# Bloque del servidor principal para HTTPS
server {
    listen 443 ssl;
    server_name bioia.redclara.net;

    ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;

    # --- Ubicación para el sitio web principal (UI) ---
    # El tráfico a bioia.redclara.net irá al contenedor 'ui'.
    location / {
        # NGINX se comunicará con el contenedor 'ui' en su puerto INTERNO 80.
        proxy_pass http://ui:80; # Correcto

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    # --- Ubicación para la API (Kraken Gateway) ---
    # El tráfico a bioia.redclara.net/api/... irá al contenedor 'kraken-gateway'.
    location /api/ {
        # NGINX se comunicará con el contenedor 'kraken-gateway' en su puerto INTERNO 9000.
        proxy_pass http://kraken-gateway:9000; # Correcto

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Configuración para keycloak
    location /realms/ {
        # Usa la IP y puerto que ya probaste que sí funcionan
        proxy_pass http://keycloak-biopatternsg:8080; 

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # ESTO ES VITAL: Cloudflare usa HTTPS, pero tu IP usa HTTP.
        # Keycloak necesita saber esto para validar el token.
        proxy_set_header X-Forwarded-Proto https;
    }

    # Sin este bloque, el link del correo cargará pero se verá en blanco (error de CSS/JS)
    location /resources/ {
        
        proxy_pass http://keycloak-biopatternsg:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

}