pipeline {
    agent any

    environment {
        NETWORK_NAME = 'general-network'
        CERT_DEST = "/etc/nginx/ssl"
    }

    stages {
        stage('Prepare Network') {
            steps {
                sh "docker network create ${NETWORK_NAME} || true"
            }
        }

        stage('Run Proxy') {
            steps {
                withCredentials([
                    file(credentialsId: 'NGINX_CRT', variable: 'CRT_FILE'),
                    file(credentialsId: 'NGINX_KEY', variable: 'KEY_FILE')
                ]){
                    script {
                        // Copiamos los secretos temporalmente al contexto de Docker para no requerir volúmenes
                        sh """
                        cp ${CRT_FILE} ./cert.crt
                        cp ${KEY_FILE} ./cert.key
                        docker compose up -d --build
                        rm -f ./cert.crt ./cert.key
                        """
                    }
                }
            }
        }
    }
}